:global:
  componentName: floodgate
  githubUrl: https://github.com/projectsyn/component-floodgate
  feature_goldenTests: true

docs/antora.yml:
  name: floodgate
  title: floodgate
.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
